source 'https://rubygems.org'

# Sinatra
gem 'sinatra'
gem 'puma'
gem 'rack-conneg'

# Mongo + Mongoid
gem 'mongo', '~> 2.1'
gem 'mongoid'
gem 'bson_ext'

# Roar/Representable
gem 'roar'
gem 'multi_json'

# Tests
gem 'rspec', '>= 1.2.1'
gem 'capybara', '>= 1.1.2'
gem 'database_cleaner'
